name: Lint and Format Check

on:
  pull_request:
  push:
    branches: [main, master, develop]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run ESLint
        run: npm run lint
        
      - name: Check formatting with Prettier
        run: npx prettier --check "src/**/*.{js,jsx,ts,tsx,css,scss,json}"
        
      - name: Setup Python for secrets scanning
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Check for secrets
        run: |
          pip install detect-secrets
          detect-secrets scan --baseline .secrets.baseline
