repos:
# Basic linting hooks
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-yaml
    -   id: check-added-large-files

# Secrets scanning with detect-secrets
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']

# ESLint for React
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.38.0
    hooks:
    -   id: eslint
        files: \.(js|jsx|ts|tsx)$
        types: [file]
        additional_dependencies:
        -   eslint@8.38.0
        -   eslint-plugin-react@7.32.2
        -   eslint-plugin-react-hooks@4.6.0
        -   eslint-config-react-app@7.0.1
        -   @typescript-eslint/eslint-plugin@5.59.0
        -   @typescript-eslint/parser@5.59.0

# Prettier for consistent formatting
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.9-for-vscode
    hooks:
    -   id: prettier
        types_or: [javascript, jsx, ts, tsx, css, scss, json]

-   repo: local
    hooks:
    -   id: test-linting
        name: Test file linting
        entry: npx eslint --config .eslintrc.test.js
        language: system
        files: \.test\.(js|jsx|ts|tsx)$
        pass_filenames: true